import Foundation

@main struct ConversationReplyTests {
    static func main() throws {
        let url = "https://claude.ai/chat/continuous"
        let old = [ChatMessage(ordinal: 1, author: .user, text: "Old question"), .init(ordinal: 2, author: .assistant, text: "Old answer")]
        var tracker = ConversationReplyTracker(baseline: old, conversation: url)
        precondition(try! tracker.observe(conversation: url, messages: old, responseComplete: true, now: 0).isEmpty)
        precondition(try! tracker.observe(conversation: url, messages: old, responseComplete: true, now: 3) == [.init(ordinal: 2, text: "Old answer")])
        print("PASS: connection automatically acquires the current complete reply")
        precondition(try! tracker.observe(conversation: url, messages: old, responseComplete: true, now: 10).isEmpty)
        print("PASS: unchanged snapshots do not translate a reply twice")
        let first = old + [.init(ordinal: 3, author: .user, text: "Typed directly in Claude"), .init(ordinal: 4, author: .assistant, text: "First new answer")]
        _ = try tracker.observe(conversation: url, messages: first, responseComplete: true, now: 11)
        precondition(try! tracker.observe(conversation: url, messages: first, responseComplete: true, now: 14) == [.init(ordinal: 4, text: "First new answer")])
        print("PASS: a direct Claude prompt gets its reply without reconnecting")
        let second = first + [.init(ordinal: 5, author: .user, text: "Another direct prompt"), .init(ordinal: 6, author: .assistant, text: "Second answer")]
        _ = try tracker.observe(conversation: url, messages: second, responseComplete: true, now: 15)
        precondition(try! tracker.observe(conversation: url, messages: second, responseComplete: true, now: 18) == [.init(ordinal: 6, text: "Second answer")])
        precondition(tracker.isCurrent(.init(ordinal: 4, text: "First new answer")))
        print("PASS: later turns preserve earlier completed reply jobs")
        var streaming = ConversationReplyTracker(baseline: [], conversation: url)
        _ = try streaming.observe(conversation: url, messages: first, responseComplete: false, now: 0)
        let early = try streaming.observe(conversation: url, messages: first, responseComplete: false, now: 30)
        precondition(!early.contains(where: { $0.ordinal == 4 }))
        _ = try streaming.observe(conversation: url, messages: first, responseComplete: true, now: 31)
        precondition(try! streaming.observe(conversation: url, messages: first, responseComplete: true, now: 34).contains(.init(ordinal: 4, text: "First new answer")))
        print("PASS: a stable pause during generation is not a complete reply")
        var batch = ConversationReplyTracker(baseline: [.init(ordinal: 1, author: .user, text: "First")], conversation: url)
        _ = try batch.observe(conversation: url, messages: second, responseComplete: true, now: 0)
        precondition(try! batch.observe(conversation: url, messages: second, responseComplete: true, now: 3).map(\.ordinal) == [2, 4, 6])
        print("PASS: multiple completed replies are emitted in order")
        var revised = second
        revised[5] = .init(ordinal: 6, author: .assistant, text: "Revised second answer")
        _ = try tracker.observe(conversation: url, messages: revised, responseComplete: true, now: 19)
        precondition(!tracker.isCurrent(.init(ordinal: 6, text: "Second answer")))
        precondition(try! tracker.observe(conversation: url, messages: revised, responseComplete: true, now: 22) == [.init(ordinal: 6, text: "Revised second answer")])
        print("PASS: a rewritten reply replaces its old version after becoming stable")
        do { _ = try tracker.observe(conversation: "https://claude.ai/chat/other", messages: revised, responseComplete: true, now: 23); fatalError("old tracker must not accept another conversation") }
        catch { print("PASS: old conversation tracker never accepts a different route") }
        var empty = ConversationReplyTracker(baseline: [], conversation: "https://claude.ai/new")
        precondition(try! empty.observe(conversation: "https://claude.ai/new", messages: [], responseComplete: true, now: 600).isEmpty)
        print("PASS: an empty connected conversation can wait indefinitely")
        let toolbar = ReplyNode(role: "AXToolbar", label: "Message actions", children: [.init(role: "AXButton", label: "Copy"), .init(role: "AXButton", label: "Retry")])
        precondition(!ClaudeDecoder.responseComplete(statusLabels: ["Claude finished the response"], controlLabels: ["Stop response"], latest: toolbar))
        print("PASS: a generation stop button overrides a stale finished announcement")
        precondition(ClaudeDecoder.responseComplete(statusLabels: ["Claude finished the response"], controlLabels: [], latest: nil))
        precondition(ClaudeDecoder.responseComplete(statusLabels: [], controlLabels: [], latest: toolbar))
        precondition(!ClaudeDecoder.responseComplete(statusLabels: [], controlLabels: [], latest: nil))
        print("PASS: finished announcements or final actions are required for latest replies")
        precondition(ReplyIdentity.id(conversation: url, ordinal: 2) == ReplyIdentity.id(conversation: url, ordinal: 2))
        precondition(ReplyIdentity.id(conversation: url, ordinal: 2) != ReplyIdentity.id(conversation: url + "other", ordinal: 2))
        print("PASS: reply bubble identities persist on reconnect and separate conversations")
        var queue = ReplyWorkQueue()
        let automatic = ReplyWork(candidate: .init(ordinal: 4, text: "New reply"), conversation: url)
        let historical = ReplyWork(candidate: .init(ordinal: 2, text: "Old reply"), conversation: url, manual: true)
        queue.add(automatic); queue.add(historical); queue.add(historical)
        precondition(queue.pop() == historical && queue.pop() == automatic && queue.pop() == nil)
        print("PASS: a selected history reply is queued without duplicating or dropping automatic replies")
        queue.add(automatic); queue.add(historical); queue.removeAutomatic()
        precondition(queue.pop() == historical && queue.pop() == nil)
        print("PASS: conversation switches retire automatic jobs while preserving selected history work")
        let viewport = CGRect(x: 0, y: 100, width: 500, height: 400)
        precondition(VisibleReplyGeometry.intersects(CGRect(x: 0, y: 0, width: 500, height: 250), viewport: viewport))
        precondition(!VisibleReplyGeometry.intersects(CGRect(x: 0, y: -500, width: 500, height: 250), viewport: viewport))
        precondition(!VisibleReplyGeometry.intersects(CGRect(x: 0, y: 499, width: 500, height: 100), viewport: viewport))
        print("PASS: history selection includes visible reply bodies and excludes offscreen or one-pixel edges")
        print("15 continuous reply tests passed")
    }
}
